### ISSUE TITLE
Uncaught Error: Call to undefined function 

### ISSUE THREAD

**Issue by ghost** [Anonyymi/minilauta-tinyib#1]
Fatal error: Uncaught Error: Call to undefined function ChrisKonnertz\BBCode\mb_strlen() in /var/www/example.org/min/inc/bbcode/BBCode.php:148 Stack trace: #0 /var/www/example.org/min/imgboard.php(396): ChrisKonnertz\BBCode\BBCode->render() #1 {main} thrown in /var/www/example.org/min/inc/bbcode/BBCode.php on line 148

/////////////////////////////////////
I can not even post a single thing with your fork as is, so i am unable to see what changes you did or are trying to do. im on latest php ver. Can you maybe include in the readme what your code changes are geared to do? Also feel free to grab my css from my repo called adelia.

**Comment by Anonyymi** [comment]
I'm sorry but I don't plan on developing my fork of tinyib any further. TinyIB is such a messy software that it's a pain to implement features for it. I'm working on my own minimalistic board that looks like TinyIB here: https://github.com/Anonyymi/miniboard

Anyways, if you still wish to see how I've got this tinyib fork of mine installed and running, check this repository: https://github.com/Anonyymi/minilauta-ansible

Or you can check out my live imageboard here: https://minilauta.org - which is running this exact code.

edit: Well I updated the README, but I'm sure I forgot something. It's intentional that this repository does not contain my git history, sorry about that.

**Comment by ghost** [comment]
Yeah, tinyib  flatfile mode is a third party script made about 14 years ago, same with simple captcha. It is very messy. Having the 3 db modes makes it harder to keep up to each new ver of php and introduces security risks too. I KNEW you would say to go to https://minilauta.org/ by the way :)  If you want people to go there, allow tor browser to visit it. It says tor is restricted. That is not acceptable terms to check out an app made by an unknown person. I only check out apps by unknown coders with the tor browser, which is reasonable privacy for site visitors. edit//////// yeah, its funny to enable tiny ib via an ansible role. That is like converting a .pl imageboard script to wasm lol. I DO like the idea of you making a minimalist board that looks like TinyIB tho, I will keep an eye on that.  another edit//// oah and do not apologize to people for running your repo in any particular way- if everyone only ran git repos in a single way, there would be zero room for creativity!  :)

**Comment by Anonyymi** [comment]
I see, well I've had to block TOR because of malicious activity that wouldn't stop otherwise. I can understand your concerns about privacy. It's a finnish imageboard anyways, I simply recommended viewing it as a demo of the features in this repo. If you can install vagrant and virtualbox, you could spin up a local instance in few minutes with a single vagrant command.

Anyways, good luck with whatever you're doing.

**Comment by ghost** [comment]
Sometime I will see if i can view your board from a vpn, I  have about 10 different ones to try lol :) As far as 
"whatever you're doing", my biggest prob is that i have to figure out if i wanna dump php entirely, as golang seems a far more
productive choice and I like go more and more every day! :)

**Comment by Anonyymi** [comment]
Golang is a nice (type-safe) language! And it produces statically linked executables. I'd say it's a good choice, though modern PHP does still have its benefits.

**Comment by ghost** [comment]
yeah, i kinda think its best to focus on just one language! I wanna learn something entirely, for a long time. php is convenient, go is better in almost every way so its a tough choice.
